### ISSUE TITLE
PHPstan not working for php version 8.1 

### ISSUE THREAD

**Issue by krtrth** [super-linter/super-linter#3299]
I was trying to use super linter for a laravel project. it fails on composer issues 
```
2022-09-07 06:06:46 [ERROR]   Found errors in [phpstan] linter!
2022-09-07 06:06:46 [ERROR]   Error code: 255. Command output:
------
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.30. in /github/workspace/vendor/composer/platform_check.php on line 24
Fatal error: Composer detected issues in your platform: Your Composer depen
<img width="966" alt="Screenshot 2022-09-07 at 11 48 57 AM" src="https://user-images.githubusercontent.com/31122308/188803649-d8fc02d7-4986-4f58-a891-c2060b865c5f.png">
dencies require a PHP version ">= 8.1.0". You are running 7.4.30. in /github/workspace/vendor/composer/platform_check.php on line 24
```

I have already installed the composer before running super linter so that PHPcs can find all vendor files too

**Comment by pookmish** [comment]
I have this same issue but with the `phpcs` & `psaml` linters. I've since disable `psalm` since it fails to even run any other linters because of composer issue (I assume due to the php dependency).

The repository I have has a composer.json file that has a dependency on PHP >=8.0.

I am able to install composer dependencies just fine prior to using super-linter.
I've tried running on `ubuntu-latest` as well as using image containers that have PHP 8.0 & 8.1.

Here's the steps:
```      - name: Composer Install
        run: composer install -n && php -v
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          # Change to false to only validate changed files.
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PHP_PSALM: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
after the composer install finishes, I'm able to see `PHP 8.1.9 (cli)` in the output. I've tried various other methods to use php 8.0/1 but to no avail. 

I assume super-linter uses the DockerFile in the root of the repo. It is indeed installing PHP7 version. https://github.com/github/super-linter/blob/main/Dockerfile#L344

PHP 7 is now EOL and looses security support in 2 months. PHP 8 should be prioritized and it would be ideal to have a way to choose which PHP version to use.

**Comment by ferrarimarco** [comment]
Hopefully #3366 will take care of this

**Comment by lindluni** [comment]
v4.10.0 released with updated deps, including PHP
