### ISSUE TITLE
Unable to access container in ghcr.io and container no longer in DockerHub since v5.1

### ISSUE THREAD

**Issue by jonesy1234** [super-linter/super-linter#4444]
## Describe the bug

The container release to DockerHub has been removed in v5.1.0 - https://github.com/super-linter/super-linter/pull/4315 without an explanation why? I'm unable to pull the container from ghcr.io/super-linter/super-linter even after authenticating for public repo access.

## Expected behaviour

Container is available in DockerHub

## Steps to Reproduce

```
docker run ghcr.io/super-linter/super-linter:v5
Unable to find image 'ghcr.io/super-linter/super-linter:v5' locally
docker: Error response from daemon: denied.
See 'docker run --help'.
```

## Additional context

Due to the time to pull a container we previously cached the container in out Self-Hosted Runner to make the super-linter process quicker for our developers.

**Comment by monotek** [comment]
same here :(

**Comment by GoetzGoerisch** [comment]
Thx, fixed it for me.

**Comment by jonesy1234** [comment]
Can you also explain why you have stopped syncing to DockerHub? The PR doesn't explain why that action was taken at all?

**Comment by zkoppert** [comment]
@jonesy1234 Great question! I stopped syncing to DockerHub because I've been unable to obtain the GitHub account credentials to DockerHub which used to be taken care of by a previous maintainer who has since left GitHub. 

If posting to DockerHub is more desirable, I'd be interested to know and could post under a personal account.

**Comment by kaaloo** [comment]
Hi @zkoppert , it seems the image might have been flipped back to private.  I've been seeing this for a week or so:

```
❯ docker pull ghcr.io/super-linter/super-linter:v5
Error response from daemon: Head "https://ghcr.io/v2/super-linter/super-linter/manifests/v5": denied: denied
```

**Comment by zkoppert** [comment]
![Screenshot 2023-09-14 at 3 20 25 PM](https://github.com/super-linter/super-linter/assets/6935431/cc5d1a86-1469-4f96-b937-e99b644e585c)
The latest v5 was posted 3 days ago and has 4500+ downloads so I don't think others are experiencing this issue. I was unable to reproduce locally as well.

**Comment by zkoppert** [comment]
@kaaloo Are you behind any firewalls that might be blocking ghcr.io?

**Comment by kaaloo** [comment]
Hi @zkoppert thank you for jumping in!  I've traced the problem to the existence of a `ghcr.io` auth token in `~/.docker/config.json`.  In our self-hosted GitHub runners, the origin of this token is very certainly because in one of our workflows we run log in to `ghcr.io` using the supplied `GITHUB_TOKEN` in order to push a private image to `ghcr.io`.  Perhaps the token is expired and unfortunately this blocks docker from pulling a public image like superlinter?  Not quite sure but we likely need to run this part of the workflow in a container, especially since we want to use these runners for other repositories that might need to push their own private images to `ghcr.io`.  Thanks again for your help!
