### ISSUE TITLE
The name secrets.GITHUB_TOKEN is not allowed.

### ISSUE THREAD

**Issue by desteves** [super-linter/super-linter#4910]
## Describe the bug

Per [GitHub Docs](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#naming-your-secrets), "Names must not start with the GITHUB_ prefix."

When attempting to create the Environment secret named `GITHUB_TOKEN` such fails due to the above constraint.

## Expected behavior

Per, "NOTE: If you pass the Environment variable GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} in your workflow, then the GitHub Super-Linter will mark the status of each individual linter run in the Checks section of a pull request." However, I cannot create the `GITHUB_TOKEN` secret thus I cannot see the additional output.

## Steps to Reproduce

1. **Create a new Environment** 
 - Go to your GitHub repository.
 - Click on the "Settings" tab.
 - In the left sidebar, click on "Environments"
 - Click on the "New environment" button.
 - Provide a name for the environment, e.g. "demo"
 - Click on the "Configure environment" button.

2.  **Create an Environment secret:**
   - In the environment configuration page from Step 1,
   - Scroll to the "Environment secrets" section.
   - Click on the "Add secret" button.
   - Provide a name for the secret and its corresponding value.
	eg,   Name:  GITHUB_TOKEN
	      Value: github_pat_123123123
   - Click on "Add secret" to save it. ** <----------- ERRORS HERE**

## Logs

ERROR:
"Failed to add secret. Secret names must not start with GITHUB_."

## Additional context

I was able to circumvent this limitation by naming my secret something else. I suggest adopting something like `secrets.SUPER_LINTER_GITHUB_TOKEN`.

**Comment by bcdonadio** [comment]
This secret is always pre-filled for you: it is a "property" of the repository entity, not of an arbitrary user entity (not even the owner). The confusion might be because you can also have a secret variable that is also called GITHUB_TOKEN which you might use in some client of the Github API for it to act on your behalf, but then it has a different context and set of possible privileges: then it pertains to the user, which can be either your PAT or a fine-grained scoped token (yup, still probably being asked in a field with the same name).

Just use the `${{ secrets.GITHUB_TOKEN }}` expression where you might need to fill it in your workflow, no need to prepare it beforehand. And of course, still be just as careful not to disclose it.
