### ISSUE TITLE
Remove color codes from linters stdout and stderr

### ISSUE THREAD

**Issue by ChaosEternal** [super-linter/super-linter#5540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current output from shellcheck has ansi color codes, which makes the output difficult to read if not from a terminal. 

### Expected Behavior

Ability to remove the ansi-color code. 

A flag or a config is good.

**Comment by ferrarimarco** [comment]
Hi @ChaosEternal !

I think this is applicable not just for ShellCheck output, but to the whole output.

Example:

```
[0m2024-04-18 04:06:21 [0;34m[INFO][0m   Linting BASH items...[0m
[0m2024-04-18 04:06:21 [0;31m[ERROR][0m   Found errors when linting BASH. Exit code: 1.[0m
[0m2024-04-18 04:06:21 [0;34m[INFO][0m   Command output for BASH:
------

[1mIn /blahline 24:[0m
[0mtrap "rm -rf '$TEMP'" EXIT[0m
[33m.           ^---^ SC2064 (warning): Use single quotes, otherwise this expands now rather than when signalled.[0m
signalled.[0m

For more information:
  https://www.shellcheck.net/wiki/SC2064 -- Use single quotes, otherwise this...
------[0m
```

Anyway, you have a point.

**Comment by ferrarimarco** [comment]
We may start with checking if we have a terminal: `if [ -t 0 ]; then ...`

**Comment by ferrarimarco** [comment]
A complementary feature may be that the log file should respect the log level, instead of defaulting to `DEBUG`, but this is for another feature request :)

**Comment by alexanderbazhenoff** [comment]
Hi @ChaosEternal

>  to read if not from a terminal.
Where to read? :)

**FYI:** if you read a raw output from GitLab CI (for example) you may use some additional browser plugins like [RetroTxt](https://chromewebstore.google.com/detail/retrotxt/gkjkgilckngllkopkogcaiojfajanahn?hl=en-US&utm_source=ext_sidebar) for Google Chrome. Full ASCII support on specified URLs available.

Something like a `.shellcheck` file with parameters would probably do, since Shellcheck doesn't support config file from the box. Or may be a special variable with options for Shellcheck, but this is a huge work at the end to made such variables for all linters. Because you should pay attention on every single linter's output and options set at all: somethings are acceptable, something will broke wrapper scripts.

**Comment by ChaosEternal** [comment]
There are two cases,
i) we have a ci system which have (only) plain log support, those color
code doesn't display correctly
ii) there are machines that want to read the output and make meaningful
suggestions to code reviewers.

**Comment by ferrarimarco** [comment]
@ChaosEternal `v6.4.1` implements part of what you're asking, I think. See #5546 for details. Now, super-linter adds color codes to stdout only if there's a tty, and never does that in the super-linter log file. This is a step in the right direction because:

- You can enable color codes when super-linter emits logs on stdout as needed (just allocate a tty).
- The super-linter log file doesn't have color codes **for super-linter log messages** (see below for details)

The issue that's left to address is that we use what each linter emits to stdout and stderr as part of the super-linter stdout and the super-linter log file. Each linter has its own way to deal with emitting (or not) color codes: configuration, command line options, presence of a tty, on unless disabled...

This might cause some color codes to be present in the super-linter stdout or in the super-linter log file when you look at each specific linter output. An example of this is Gitleaks.

(the following statements are applicable to linters that support color codes)

To address this, we would need to account for two cases to avoid getting color codes in the super-linter stdout and super-linter log file when not needed:

- There is no tty allocated: disable color output for each individual linter. (probably doable)
- There is a tty allocated: this is harder because we would need two outputs for each linter: one for super-linter stdout (with color codes), one for super-linter log (without color codes). I don't think many linters (if at all) support this.

**Comment by ferrarimarco** [comment]
> i) we have a ci system which have (only) plain log support, those color code doesn't display correctly

See my previous reply about this.

> ii) there are machines that want to read the output and make meaningful suggestions to code reviewers.

For this, parsing text logs is probably too fragile. We might want to have a look at more structured output formats, such as SARIF and JSON for linters that support that, but that's for another feature request, I suppose. :)

**Comment by alexanderbazhenoff** [comment]
> Now, super-linter adds color codes to stdout only

BTW, how to force enable colors now in CI? (Not so big problem, but it's better for us :)

**Comment by ferrarimarco** [comment]
@alexanderbazhenoff Hi! How are you running super-linter?

**Comment by alexanderbazhenoff** [comment]
> @alexanderbazhenoff Hi! How are you running super-linter?

Hi, in GitLab CI as described [here](https://github.com/super-linter/super-linter/issues/5567#issue-2257800015).

**Comment by ferrarimarco** [comment]
@alexanderbazhenoff Can you try allocating a TTY (add `--tty` or `-t` option to the `docker run` command)?
