### ISSUE TITLE
Don't require the full Git history

### ISSUE THREAD

**Issue by brennovich** [super-linter/super-linter#5626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Version 6 requires `fetch-depth: 0`, however this is not feasible for every repo, for repos with long history a clone can take too much time.

### Expected Behavior

Be able to disable whatever lints that requires complete git history

### Super-Linter version

```markdown
v6.Y.Z
```

### Relevant log output

```shell
2024-05-06 14:23:15 [INFO]   Validating the configuration
  .git
  2024-05-06 14:23:16 [INFO]   Check that the local repository has the full history and that the repository is not shallow.
  2024-05-06 14:23:16 [INFO]   Check that you set the 'fetch-depth: 0' option for the actions/checkout step in your GitHub Actions workflow.
  2024-05-06 14:23:16 [INFO]   See https://github.com/super-linter/super-linter#get-started
  2024-05-06 14:23:16 [INFO]   Is shallow repository: true
```

### Steps To Reproduce

```
-  uses: actions/checkout@v4
```

**Comment by ferrarimarco** [comment]
Hi! This looks like an enhancement request, also considering that this particular implementation didn't change.

What changed is that we fixed a couple of bugs that prevented this error for being reported, and we improved the error message.

We don't _probably_ need the whole history, but we would be fine with the number of commits that allow super-linter to correctly get changes in case `VALIDATE_ALL_CODEBASE` is `false` (the default).

You can try setting fetch depth to a number > 0 and see if that works.

In that case, we might update the documentation to reflect that.

**Comment by ferrarimarco** [comment]
In other words, we need a number of commits that allows these two commands to run:

https://github.com/super-linter/super-linter/blob/6047e3f732ceff4c86ae4bf545e0fb57a07c2d1d/lib/functions/buildFileList.sh#L15

https://github.com/super-linter/super-linter/blob/6047e3f732ceff4c86ae4bf545e0fb57a07c2d1d/lib/functions/buildFileList.sh#L23

so super-linter can correctly get diffs.

This is something that super-linter cannot know in advance because the `actions/checkout` happens before super-linter even runs.

What super-linter might do is to require a fetch depth >0 (i.e. require that a repository is not shallow), and check if the number of commits is enough to compute the diff. Although this is not clear yet.

**Comment by ferrarimarco** [comment]
That way could potentially alter the state of the local repository, which is something that we don't want to do.

**Comment by ferrarimarco** [comment]
This is something that's out of Super-linter control. As a workaround, you might try experimenting with different `fetch-depth` values.
