### ISSUE TITLE
Make the image repository configurable to allow pull-through caches

### ISSUE THREAD

**Issue by schniedergers** [super-linter/super-linter#5825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the image used by the action is set as `docker://ghcr.io/super-linter/super-linter:<version>`.
If using the action on self-hosted runners, a docker image "pull through cache" is common practice in cloud environments, to reduce the load on the "origin" image repository (ghcr.io) and to speed up image pulls on the self-hosted runners.

E.g. Artifactory or AWS-ECR pull-through are such caches. To use them, the action needs to use a different repository. I do not see a way to overwrite the `ghcr.io/super-linter` repository without forking the helm chart.

### Expected Behavior

I'd expect a way to set a repository for the image repository (and maybe the image tag), e.g. via an environment variable.
The default should remain `docker://ghcr.io/super-linter/super-linter`.

**Comment by ferrarimarco** [comment]
Hi @schniedergers!

I don't think this is supported by GitHub actions: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsimage

A possible workaround might be to run Super-linter as a step in your workflow using a container runtime (such as Docker), directly to run Super-linter, instead of using the action. Ref: https://github.com/super-linter/super-linter?tab=readme-ov-file#run-super-linter-outside-github-actions
