### ISSUE TITLE
Formalize and publish a more structured and public release cadence

### ISSUE THREAD

**Issue by mikelax** [super-linter/super-linter#5924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As a user of super-linter, it would be helpful to know what the release cadence is, and when new versions will be published. 

The reason for this is that there currently is an unknown amount of lag between when a new version of a given linter is published, and when a super-linter version will be published that includes the updated linter version. 

For reference: 

- [This checkov issue](https://github.com/bridgecrewio/checkov/issues/6172) was fixed on July 3, 2024 and published in checkov version `3.2.171`
- super-linter was updated in #5879 on July 16, 2024 with a version of checkov that includes this fix
- As of July 23, 2024 super-linter version has not been published with this fix, unknown at this point when the next release will be. 

Because of this, as a developer I am either forced to wait, or ignore the given rule temporarily and then remember to circle and re-enable this rule at a later point in time.

Please see [this discussion thread](https://github.com/super-linter/super-linter/discussions/5922) for more context about this request. 

### Expected Behavior

Ideally, there was a release calendar for the project so I could be aware of when the next scheduled release will be. I can then make a decision on how to proceed with either waiting for the next version, ignoring rules, etc.

**Comment by echoix** [comment]
It might be useful to note that checkov is kind of a special case: it has releases almost every day, and can have multiple releases in a single day. Keeping up is not practical, so there would be jumps. Limiting to minor versions for checkov doesn't make sense, the 3.2.x releases started at the end of January, with about 200 releases since (as of today).

**Comment by ferrarimarco** [comment]
I think this request has a point. Now that releases are fully automated (although manually initiated), we can think about this.

As a workaround, you can use either the `latest` image, but you'll lose build reproducibility, or a specific image hash that the `latest` tag points to, but you'll have more management overhead to keep it up to date (mitigated by dependency update automation tools, such as Renovate and DependaBot). In both cases, you might pay the price of depending on a less stable container image.

**Comment by ferrarimarco** [comment]
Worth noting that currently, Super-linter dependency updates PRs are scheduled weekly (initially introduced in #1544), [on Mondays (default config)](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval).

Also, in addition to the usual (not yet formalized, as well) SemVer release convention, in the last few releases we're experimenting with a different dependency update grouping:

- Super-linter patch releases can include only patch linter updates.
- Super-linter major or minor releases can include any linter update (major, minor, or patch).

**Comment by ferrarimarco** [comment]
Looping @zkoppert and @Hanse00 because we might want to formalize this at a project level. Thanks!

**Comment by zkoppert** [comment]
My opinion:
- I don't prefer to have scheduled releases (every Friday) because I find that it tends to hold up things rather than deliver them when they are actually available.
- I think we should ensure that when significant code changes are available (major and minor) a release is created and if someone wants patch updates they can switch to latest. This strikes a balance between release spamming (large number of releases per day that may each create downstream dependabot pull requests and be very annoying to users) and shipping updates in a timely manner.

Does that make sense? Am I missing something important in my understanding of the problem?

**Comment by Hanse00** [comment]
I think there's a point to distinguishing between the two potential drivers for releases of our application, and how we want to handle them.

* Code changes we make to the actual superlinter codebase
* Dependency updates that require us to release a new version utilizing that dependence

In the first case, I absolutely agree with @zkoppert that a fixed cadence isn't the right move. We make changes when we do, and release them when they're ready. We should neither artificially hold back changes to match the cadence, nor push out new code that isn't ready because of the timing.

But I don't get the impression that's actually what we're discussing here.

In the second case, there is in my opinion a significant and valid question of: How do we balance not shipping outdated dependencies, and keeping people waiting, with not making it burdensome for us and downstream users to deal with the sheer volume of releases?

For better or worse, we've painted ourselves into a bit of a corner as being the "one stop shop for linters" also means we have a large number of upstream dependencies to deal with, and our downstream users probably want those to be fairly fresh.

Putting aside a larger commentary on the software dependency ecosystem at large, given that is currently where we stand, I think doing *something* to ensure we release new dependencies relatively often is warranted.

@ferrarimarco I don't have a strict opinion on how we communicate this in the version identifier, but I'm inclined towards the concept of logically separating "Is this an update to superlinter" (the product) vs. "Is this superlinter updating the linters it uses", and in doing so I would feel comfortably more regularly releasing versions that only update dependencies, in an automated manner.

**Comment by zkoppert** [comment]
One thing we could do to aid users in the case we want to increase our volume/frequency of releases is to add into our `README.md` a disclaimer of sorts on how to configure dependabot to control the pull request frequency to update super-linter.

**Comment by ferrarimarco** [comment]
Thanks for your inputs, I think we're all on the same page.

Personally, when managing dependency updates, I try to merge them right before crafting a new release, so we avoid duplicate work (and polluting release notes) when we update linters several times before releasing.

Considering two different approaches for updates to Super-linter (the "product") and to dependencies makes sense to me.

Even if we recently shipped several new features and bug fixes to Super-linter the volume of changes is still low in this regard. I think we can still go with an ad-hoc release strategy in this case.

When dealing with dependency updates, we can think about scheduling something, along with an ad-hoc approach?
